msm8974: Satisfy libc2dcolorconvert dependencies
hardware/qcom/media/msm8974/libc2dcolorconvert/C2DColorConverter.cpp:34:10: fatal error: 'linux/msm_kgsl.h' file not found
Since our kernel objects are built early we can satisfy this dependency from there.